import { OrderStatus } from "@/types";

type OrderStatusInfo = {
  label: string;
  value: OrderStatus;
  progressValue: number;
};

export const ORDER_STATUS: OrderStatusInfo[] = [
  { label: "Placed", value: "placed", progressValue: 0 },
  {
    label: "Awaiting Restaurant Confirmation",
    value: "paid",
    progressValue: 25,
  },
  { label: "In Progress", value: "inProgress", progressValue: 50 },
  { label: "Out for Delivery", value: "outForDelivery", progressValue: 75 },
  { label: "Delivered", value: "delivered", progressValue: 100 },
];

export const cuisineList: string[] = [
  "American",
  "Andhra",
  "Arabian",
  "Asian",
  "Assamese",
  "Awadhi",
  "Bakery",
  "Barbecue",
  "Bengali",
  "Beverages",
  "Bihari",
  "Biryani",
  "British",
  "Bubble Tea",
  "Burgers",
  "Burmese",
  "Cafe",
  "Cakes & Pastries",
  "Cakes and Pastries",
  "Chaat",
  "Chettinad",
  "Coastal",
  "Coffee",
  "Combo",
  "Continental",
  "Default",
  "Desserts",
  "European",
  "Fast Food",
  "French",
  "German",
  "Goan",
  "Grill",
  "Gujarati",
  "Haleem",
  "Healthy Food",
  "Home Food",
  "Hyderabadi",
  "Ice Cream",
  "Ice Cream Cakes",
  "Indian",
  "Indonesian",
  "Italian",
  "Italian-American",
  "Jain",
  "Japanese",
  "Juices",
  "Kashmiri",
  "Kebabs",
  "Kerala",
  "Keroylian",
  "Lebanese",
  "Lucknowi",
  "Maharashtrian",
  "Malaysian",
  "Mangalorean",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Momos",
  "Mughlai",
  "Navratri Special",
  "Nepalese",
  "North Eastern",
  "North Indian",
  "Oriental",
  "Oriya",
  "Paan",
  "Pan-Asian",
  "Pastas",
  "Pizzas",
  "Portuguese",
  "Punjabi",
  "Rajasthani",
  "Rayalaseema",
  "Rolls & Wraps",
  "Salads",
  "Seafood",
  "Shawarma",
  "Singaporean",
  "Snacks",
  "South American",
  "South Indian",
  "Steakhouse",
  "Street Food",
  "Sushi",
  "Sweets",
  "Tandoor",
  "Tea",
  "Telangana",
  "Tex-Mex",
  "Thai",
  "Thalis",
  "Tibetan",
  "Turkish",
  "Vietnamese",
  "Waffle",
  "briyani",
  "fastfood",
  "jar cakes",
  "juice",
  "paratha",
  "pav bhaji",
  "pizza",
  "rolls",
  "sandwich",
];
